# The version of the config.yml file. This is used to check if the config.yml file is up-to-date.
# Useful if you want to manually update config.yml without deleting the old one.
version: 2

# Print the response after forwarding a message to Guilded
debug: false

# The language to use for the plugin.
# Go to https://github.com/MCUmbrella/MGBridge/tree/main/src/main/resources to see the available languages.
# Language files are named "lang_xx_XX.yml" where "xx" is the language code and "XX" is the country code.
language: "en_US"

# Your bot token. You can get one from "Server Settings -> Bots -> (bot name) -> Manage auth tokens"
token:

# Target server ID. The plugin will only detect messages sent from this server
server:

# Target channel UUID. Message forwarding and '/mgb' command works in this channel.
channel:

# The format of the chat messages sent from Minecraft to Guilded.
# You can use the following variables: {PLAYER}, {MESSAGE}
# You can disable forwarding messages from Minecraft to Guilded by setting this to "disabled"
toGuildedMessageFormat: "**{PLAYER} ⟫** {MESSAGE}"

# The format of the chat messages sent from Guilded to Minecraft.
# You can use the following variables: {PLAYER}, {MESSAGE}
# You can disable forwarding messages from Guilded to Minecraft by setting this to "disabled"
toMinecraftMessageFormat: "[§eGuilded§r] <{PLAYER}> {MESSAGE}"

# Forward player join/quit messages
forwardJoinLeaveEvents: true

# Proxy configuration settings.
proxy:
  # Connect to Guilded with proxy? If you don't need a proxy, set this to "direct".
  # Available values are: "default", "direct", "http", "socks".
  # Use "default" to automatically detect proxy settings from JVM arguments.
  type: "default"
  # Proxy address (e.g. "127.0.0.1:1080")
  address: "127.0.0.1:1080"

# If the WebSocket connection is lost, the plugin will attempt to reconnect every this amount of seconds
reconnectDelay: 3
