name: MGBridge
version: ${project.version}
main: vip.floatationdevice.mgbridge.MGBridge
api-version: 1.13
authors: [ MCUmbrella ]
website: https://github.com/MCUmbrella/MGBridge
commands:
  mgb:
    description: The main command of MGBridge
permissions:
  mgbridge.mkbind:
    description: Allows the user to bind to Guilded account
    default: true
  mgbridge.rmbind:
    description: Allows the user to unbind from Guilded account
    default: true
  mgbridge.reload:
    description: Allows the user to reload the plugin
    default: op