name: MGBridge
version: ${project.version}
main: vip.floatationdevice.mgbridge.MGBridge
api-version: 1.13
authors: [ MCUmbrella ]
website: https://github.com/MCUmbrella/MGBridge
commands:
  mgb:
    description: The main command of MGBridge
